LMS/Controllers/LoansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LMS.Models;
using Model;
using Vereyon.Web;

namespace LMS.Controllers
{
    public class LoansController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Loans
        public ActionResult Index(string option, string search)
        {
            if (option == "id")
            {
                int memberId = 0;
                if (search != null)
                {
                    memberId = Convert.ToInt32(search);

                }
                var loans = db.Loans.Include(l => l.Books).Include(l => l.Members).Where(x => x.MemberId == memberId);
                return View(loans.ToList());

            }
            else if (option == "memberName")
            {
                var loans = db.Loans.Include(l => l.Books).Include(l => l.Members).Where(x => x.Members.FirstName == search || x.Members.LastName == search);
                return View(loans.ToList());
            }
            else if (option == "bookTitle")
            {
                var loans = db.Loans.Include(l => l.Books).Include(l => l.Members).Where(x => x.Books.Name == search);
                return View(loans.ToList());
            }

            else
            {
                var loans = db.Loans.Include(l => l.Books).Include(l => l.Members);
                return View(loans.ToList());
            }

        }

        // GET: Loans/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loan loan = db.Loans.Find(id);
            if (loan == null)
            {
                return HttpNotFound();
            }
            return View(loan);
        }

        // GET: Loans/Create
        public ActionResult Create()
        {
            ViewBag.BookId = new SelectList(db.Books, "Id", "Name");
            ViewBag.MemberId = new SelectList(db.Members, "Id", "FirstName");
            return View();
        }

        // POST: Loans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,BookId,LoanOn,Quantity,DateReturned,AgeRestricted,MemberId")] Loan loan)
        {
            if (ModelState.IsValid)
            {
                var books = db.Books.Find(loan.BookId);
                //var loans = db.Loans.Find(loan.BookId);
                var loans = db.Loans.Where(x => x.BookId == loan.BookId).FirstOrDefault();
                ViewBag.BookId = new SelectList(db.Books, "Id", "Name", loan.BookId);
                ViewBag.MemberId = new SelectList(db.Members, "Id", "FirstName", loan.MemberId);
                //if (loanQuantity > 0)
                //{
                //    FlashMessage.Warning("The book is not available currenlty!");
                //    return View(loan);
                //}
                if (books == null)
                {
                    FlashMessage.Warning("The book is not on the shelf currently!!");

                    return View(loan);
                }
                if (loans != null)
                {
                    int bookOnShelf = books.Quantities - loans.Quantity;

                    if (bookOnShelf < loan.Quantity)
                    {
                        FlashMessage.Warning(@"We have {0} books on the shelf currently!", bookOnShelf);

                        return View(loan);
                    }
                }

                //if (books.Quantities <= loanQuantity)
                //{
                //    FlashMessage.Warning("The Quantity of the book is less on the shelf!");
                //    return View(loan);

                //}
                db.Loans.Add(loan);
                db.SaveChanges();

                return RedirectToAction("Index");
            }


            return View(loan);
        }

        // GET: Loans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loan loan = db.Loans.Find(id);
            if (loan == null)
            {
                return HttpNotFound();
            }
            ViewBag.BookId = new SelectList(db.Books, "Id", "Name", loan.BookId);
            ViewBag.MemberId = new SelectList(db.Members, "Id", "FirstName", loan.MemberId);
            return View(loan);
        }

        // POST: Loans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,BookId,LoanOn,Quantity,DateReturned,MemberId")] Loan loan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(loan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BookId = new SelectList(db.Books, "Id", "Name", loan.BookId);
            ViewBag.MemberId = new SelectList(db.Members, "Id", "FirstName", loan.MemberId);
            return View(loan);
        }

        // GET: Loans/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loan loan = db.Loans.Find(id);
            if (loan == null)
            {
                return HttpNotFound();
            }
            return View(loan);
        }

        // POST: Loans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Loan loan = db.Loans.Find(id);
            db.Loans.Remove(loan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LMS/Views/Loans/Create.cshtml
@model Model.Loan

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Loan</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.BookId, "BookId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("BookId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.BookId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LoanOn, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LoanOn, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LoanOn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateReturned, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateReturned, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateReturned, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Books.AgeRestricted, "Age Restricted", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Books.AgeRestricted, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Books.AgeRestricted, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.MemberId, "MemberId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MemberId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MemberId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LMS/Views/Loans/Delete.cshtml
@model Model.Loan

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Loan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Books.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Books.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Members.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Members.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoanOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoanOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateReturned)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateReturned)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LMS/Views/Loans/Details.cshtml
@model Model.Loan

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Loan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Books.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Books.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Members.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Members.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoanOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoanOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateReturned)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateReturned)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LMS/Views/Loans/Edit.cshtml
@model Model.Loan

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Loan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.BookId, "BookId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BookId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BookId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoanOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoanOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoanOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateReturned, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateReturned, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateReturned, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberId, "MemberId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MemberId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MemberId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LMS/Views/Loans/Index.cshtml
@model IEnumerable<Model.Loan>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Loans", FormMethod.Get))
{
    //the following are search options
    <b> Search Option: </b>
    @Html.RadioButton("option", "memberName")<text>Member Name</text>
    @Html.RadioButton("option", "id")<text>Member Id</text>
    @Html.RadioButton("option", "bookTitle")<text>Book Title</text>
    @Html.TextBox("search")

    <input type="submit" name="submit" value="Search" />
}
<table class="table">
    <tr>
        <th>
           Book Title
        </th>
        <th>
            Members Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LoanOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.DateReturned)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Books.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Members.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoanOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.DateReturned)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>